export const assets = {
  glassesMobile: require('./glasses-photo-mobile.jpg'),
  glassesPhoto0: require('./glasses-photo-0.jpg'),
  glassesPhoto1: require('./glasses-photo-1.jpg'),
  glassesPhoto2: require('./glasses-photo-2.jpg'),
  hatsMobile: require('./hats-photo-mobile.jpg'),
  hatsPhoto0: require('./hats-photo-0.jpg'),
  hatsPhoto1: require('./hats-photo-1.jpg'),
  hatsPhoto2: require('./hats-photo-2.jpg'),
  jantiesMobile: require('./janties-photo-mobile.jpg'),
  jantiesPhoto0: require('./janties-photo-0.jpg'),
  jantiesPhoto1: require('./janties-photo-1.jpg'),
  jantiesPhoto2: require('./janties-photo-2.jpg'),
  masksMobile: require('./masks-photo-mobile.jpg'),
  masksPhoto0: require('./masks-photo-0.jpg'),
  masksPhoto1: require('./masks-photo-1.jpg'),
  masksPhoto2: require('./masks-photo-2.jpg'),
  storyMobile: require('./story-photo-mobile.jpg'),
  storyPhoto0: require('./story-photo-0.jpg'),
  aboutMobile: require('./about-photo-mobile.jpg'),
  aboutPhoto0: require('./about-photo-0.jpg'),
  aboutPhoto1: require('./about-photo-1.jpg'),
  aboutPhoto2: require('./about-photo-2.jpg'),
};